### ISSUE TITLE
make less_than_vector a const member function:

### ISSUE THREAD

**Issue by dcompara** [FangjiW/BBMOCBS-approx#2]
I got a compilation error. To solve it I add to make the 

struct less_than_vector  const so

struct less_than_vector {
    bool operator()(const std::vector<unsigned long long>& a, const std::vector<unsigned long long>& b) const { // Note the const at the end
        // Comparison logic here
    }
};

**Comment by FangjiW** [comment]
Thanks, I have changed this.
